version: "3"

services:
    db:
      image: postgres:12.2-alpine
      container_name: pg-sandbox-db
      restart: always
      environment:
        - POSTGRES_PASSWORD=db
        - POSTGRES_USER=db
      volumes:
        - ./data-sources:/data-sources
        - ./db-data:/var/lib/postgresql/data
      command:
        - -c
        - shared_preload_libraries=pg_stat_statements
        - -c
        - pg_stat_statements.max=10000
        - -c
        - pg_stat_statements.track=all

    dbadmin:
      image: dpage/pgadmin4
      container_name: pg-sandbox-dbadmin
      restart: always
      ports:
        - 8036:80
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin
        - PGADMIN_DEFAULT_PASSWORD=123456
      depends_on:
        - db
